# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadenzauser',
            name='tracker_name',
            field=models.CharField(blank=True, default='My first tracker', max_length=50),
        ),
    ]
