# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 05:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('motif', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='user',
        ),
        migrations.RemoveField(
            model_name='textmsg',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='TextMsg',
        ),
    ]
